### ISSUE TITLE
Bootstrap version is not configured

### ISSUE THREAD

**Issue by GeorgeB123** [bootstrap-ruby/middleman-bootstrap-navbar#5]
Hey, I am using middleman 4.2.1 and middleman-bootstrap-navbar 3.0.2. I am getting the error Bootstrap version not configured when trying to run activate :bootstrap_navbar in config.rb. I have been struggling for the past day and can't figure this out. Here is my Gemfile:

gem "middleman", "~>4.2.1"

gem "middleman-livereload", "~> 3.1.0"

gem "middleman-sprockets", "~> 4.1.0"

gem 'middleman-bootstrap-navbar', "3.0.2"

gem "redcarpet", "~> 2.2.2"

gem "middleman-syntax", "~> 3.0.0"

Any help would be much appreciated.

**Comment by manuelmeurer** [comment]
You need to set the Bootstrap version, [as described in the README](https://github.com/bootstrap-ruby/middleman-bootstrap-navbar#set-bootstrap-version).

**Comment by GeorgeB123** [comment]
I still get the same error when i set 
activate :bootstrap_navbar do |bootstrap_navbar|
  bootstrap_navbar.bootstrap_version = '3.0.2'
end
Is there elsewhere I need to set the bootstrap version?
I keep getting this error:
RuntimeError: Bootstrap version is not configured.
  /usr/local/lib/ruby/gems/2.4.0/gems/bootstrap-navbar-2.5.0/lib/bootstrap-navbar/helpers.rb:5:in `included'

**Comment by manuelmeurer** [comment]
I can't recreate the problem. Can you upload a sample project where this happens to GitHub?

**Comment by manuelmeurer** [comment]
I'll close this for now. Feel free to reopen if you still have this problem.

**Comment by mig5** [comment]
Getting the same issue with the latest version of this gem and bootstrap-navbar gem 3.2.1.

**Comment by manuelmeurer** [comment]
Can you try bootstrap-navbar 3.2.2?

**Comment by manuelmeurer** [comment]
If not, could you set up a simple middleman project that recreates this problem?

**Comment by mig5** [comment]
I get the same error with 3.2.2 (which exists in Rubygems but not on their Github site, ~~a bit scary, hope it's not a compromised version)~~ EDIT: just saw your note in https://github.com/bootstrap-ruby/bootstrap-navbar/issues/25#issuecomment-2654874421 ! Thanks!

```
user:/webapps/documentation-site/docs [!?] via 💎 v3.0.2 as 🧙 ❯ bundle exec middleman
/var/lib/gems/3.0.0/gems/bootstrap-navbar-3.2.2/lib/bootstrap-navbar/helpers.rb:13:in `included': Could not determine Bootstrap version from gems or Node package. (RuntimeError)
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension.rb:373:in `include'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension.rb:373:in `block in expose_methods'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension.rb:372:in `each'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension.rb:372:in `expose_methods'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension.rb:313:in `initialize'
	from /var/lib/gems/3.0.0/gems/middleman-bootstrap-navbar-4.0.0/lib/middleman-bootstrap-navbar/extension.rb:19:in `initialize'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension_manager.rb:66:in `new'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/extension_manager.rb:66:in `activate'
	from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `activate'
	from /webapps/dev/docs/config.rb:99:in `evaluate_configuration!'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/application.rb:329:in `instance_eval'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/application.rb:329:in `evaluate_configuration!'
	from /var/lib/gems/3.0.0/gems/middleman-core-4.4.3/lib/middleman-core/application.rb:286:in `initialize'
	from /var/lib/gems/3.0.0/gems/middleman-cli-4.4.3/bin/middleman:49:in `new'
	from /var/lib/gems/3.0.0/gems/middleman-cli-4.4.3/bin/middleman:49:in `<top (required)>'
	from /usr/local/bin/middleman:25:in `load'
	from /usr/local/bin/middleman:25:in `<main>'
```

In my Gemfile.lock there is (among other things)

```
    bootstrap-navbar (3.2.2)
      gem_config (~> 0.3)

    middleman-bootstrap-navbar (4.0.0)
      bootstrap-navbar (~> 3.0)
      middleman (>= 3.1)


    middleman (4.4.3)
      coffee-script (~> 2.2)
      haml (>= 4.0.5, < 6.0)
      kramdown (>= 2.3.0)
      middleman-cli (= 4.4.3)
      middleman-core (= 4.4.3)
```


In my config.rb I have (among other things)

```
activate :bootstrap_navbar do |bootstrap_navbar|
  bootstrap_navbar.bootstrap_version = '3.3.5'
end
```

I'm 'inheriting' a middleman app from someone else. It worked on ruby2.7 before I upgraded from Ubuntu 20.04 to 22.04 and started trying to upgrade the gems. It would take me some time to put together a sample project, but I'll see what I can do.

**Comment by manuelmeurer** [comment]
Could you try replacing the `activate` call in your config.rb with this?

```
::BootstrapNavbar.configure do |config|
  config.bootstrap_version = '3.3.5'
end
activate :bootstrap_navbar
```

This should work with Middleman v4, I think I simply forgot to update the README.

**Comment by mig5** [comment]
Thank you @manuelmeurer ! That has fixed this issue. (I have other failures now but it's not with this gem). Thank you for unblocking me!

**Comment by manuelmeurer** [comment]
Good to hear! :) I updated the README.
